In [41]:
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split

In [42]:
path = '/home/ubuntu/Mestrado/modelo_foguete/model/engines/decision_tree_model.pkl'
path = '/home/ubuntu/Mestrado/modelo_foguete/improve_exec_speed/data/DecisionTreeRegressor_score_1.0.joblib'
model = joblib.load(path)

In [43]:
data_path = '/home/ubuntu/Mestrado/modelo_foguete/improve_exec_speed/data/grid_target.csv'
df_grid_target = pd.read_csv(data_path)

# Processa e converte para numpy
X_y = df_grid_target.to_numpy()
X = X_y[:,0:3]
y = X_y[:,3:]

# Deleta o dataframe para liberar espaco na RAM
del df_grid_target

# Divide os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [44]:
X_train

array([[0.56565657, 0.68686869, 0.53535354],
       [0.38383838, 0.23232323, 0.11111111],
       [0.24242424, 0.15151515, 0.19191919],
       ...,
       [0.13131313, 0.19191919, 0.32323232],
       [0.67676768, 0.11111111, 0.55555556],
       [0.12121212, 0.19191919, 0.58585859]])

In [16]:
import numpy as np
import statsmodels.api as sm

# Adicionando uma coluna de uns para intercepto aos dados de teste
X_test_with_intercept = sm.add_constant(X_test, has_constant='add')

# Fazendo previsões com o modelo sklearn para usar no OLS de statsmodels
predictions = model.predict(X_test)

# Ajustando o modelo OLS com os mesmos dados usados para previsões
ols_model = sm.OLS(y_test, X_test_with_intercept).fit()

# Obtendo o sumário do modelo, que inclui os p-values
print(ols_model.summary())

# Se você quiser apenas os p-values, sem o sumário completo
p_values = ols_model.pvalues
print(p_values)


ValueError: shapes (200000,3) and (5,) not aligned: 3 (dim 1) != 5 (dim 0)

In [37]:
import statsmodels.api as sm

# Supondo que X_test seja seus dados de teste e y_test seja um array com 6 dimensões
# Cada coluna de y_test representa uma variável dependente diferente

p_values_all = []  # Para armazenar os p-values de cada modelo

for i in range(y_test.shape[1]):  # Assumindo que y_test é um DataFrame ou numpy array com 6 colunas
    # Seleciona a i-ésima coluna de y_test como a variável dependente
    y = y_test[:, i]
    
    # Adiciona um intercepto à matriz X_test
    X_with_intercept = sm.add_constant(X_test)
    
    # Ajusta o modelo OLS para a i-ésima variável dependente
    model = sm.OLS(y, X_with_intercept).fit()
    
    # Armazena os p-values deste modelo
    p_values = model.pvalues
    p_values_all.append(p_values)
    
    # Opcional: Imprimir o sumário para este modelo específico
    print(f"Modelo para a dimensão {i+1}")
    print(model.summary())
    print("\n" + "="*80 + "\n")

# p_values_all agora contém os p-values para cada modelo ajustado a cada variável dependente


Modelo para a dimensão 1
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.376
Model:                            OLS   Adj. R-squared:                  0.376
Method:                 Least Squares   F-statistic:                 4.024e+04
Date:                Sat, 24 Feb 2024   Prob (F-statistic):               0.00
Time:                        02:37:24   Log-Likelihood:            -1.0021e+06
No. Observations:              200000   AIC:                         2.004e+06
Df Residuals:                  199996   BIC:                         2.004e+06
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        210.5404      

In [26]:
# Printa o R-squared para cada uma das variáveis do modelo usando sklearn
from sklearn.metrics import r2_score
predictions = model.predict(X_test)

print(predictions)

# for i in range(y_test.shape[1]):
#     y = y_test[:, i]
#     r2 = r2_score(y, predictions[i])
#     print(f"R-squared para a dimensão {i+1}: {r2}")
    

ValueError: shapes (200000,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)

In [40]:
model.predict(X_test)

ValueError: shapes (200000,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)

In [46]:
predictions = model.predict(X_test)


In [47]:
from sklearn.metrics import r2_score


In [51]:
y_test[:, i].shape, predictions[:,i].shape

((200000,), (200000,))

In [59]:
i=1
r2_score(y_test[:, i], predictions[:,i])

0.9994155262395149

In [60]:
# Calcula o p_score das predicoes

p_values_all = []  # Para armazenar os p-values de cada modelo

for i in range(y_test.shape[1]):  # Assumindo que y_test é um DataFrame ou numpy array com 6 colunas

    # Seleciona a i-ésima coluna de y_test como a variável dependente
    y = y_test[:, i]

    # Adiciona um intercepto à matriz X_test
    X_with_intercept = sm.add_constant(X_test)

    # Ajusta o modelo OLS para a i-ésima variável dependente
    model = sm.OLS(y, X_with_intercept).fit()

    # Armazena os p-values deste modelo
    p_values = model.pvalues
    p_values_all.append(p_values)

    # Opcional: Imprimir o sumário para este modelo específico
    

In [61]:
p_values_all

[array([0., 0., 0., 0.]),
 array([0., 0., 0., 0.]),
 array([0.        , 0.        , 0.        , 0.51547577]),
 array([0.      , 0.      , 0.      , 0.405947]),
 array([0.        , 0.        , 0.        , 0.59554129]),
 array([0.        , 0.        , 0.        , 0.27879546])]

In [62]:
i=1
y_test[:, i], predictions[:,i]

(array([300.82271395, 275.82568994, 302.10897711, ..., 346.59421993,
        354.75891483, 299.50593318]),
 array([300.44838695, 275.68348047, 302.48338718, ..., 344.95754775,
        354.53832097, 299.30511875]))